apiVersion: v2
name: redis-sharded
description: A Helm chart for sharded redis
type: application
version: 0.5.0
appVersion: 8.10.1
icon: https://cdn.worldvectorlogo.com/logos/redis.svg
keywords:
  - redis
  - shard
