apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis-sharded.fullname" . }}
  labels:
    {{- include "redis-sharded.labels" . | nindent 4 }}
data:
  redis.conf: |-
{{- if .Values.configmap }}
{{ tpl .Values.configmap . | indent 4 }}
{{- end }}
---
